-- auto Generated on 2021-03-02
-- DROP TABLE IF EXISTS t_function;
CREATE TABLE t_function(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	function_name VARCHAR (255) NOT NULL DEFAULT '' COMMENT '功能名称',
	function_code VARCHAR (255) NOT NULL DEFAULT '' COMMENT '功能编号',
	function_type INT (11) NOT NULL DEFAULT 0 COMMENT 'functionType',
	chargeman VARCHAR (255) NOT NULL DEFAULT '' COMMENT 'chargeman',
	descirption VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'descirption',
	add_user VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'addUser',
	add_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'addTime',
	update_user VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'updateUser',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 't_function';
