-- auto Generated on 2021-02-22
-- DROP TABLE IF EXISTS t_dict;
CREATE TABLE t_dict(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	dict_code VARCHAR (50) NOT NULL DEFAULT '' COMMENT '编码',
	dict_value VARCHAR (50) NOT NULL DEFAULT '' COMMENT '值',
	dict_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT '名称',
	category_code VARCHAR (50) NOT NULL DEFAULT '' COMMENT '类型编码',
	sort_no INT (11) NOT NULL DEFAULT -1 COMMENT '排序',
	`status` INT (11) NOT NULL DEFAULT -1 COMMENT '状态',
	remark VARCHAR (50) NOT NULL DEFAULT '' COMMENT '字典描述',
	add_time DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'addTime',
	add_user VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'addUser',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
	update_user VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'updateUser',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 't_dict';
