-- auto Generated on 2021-03-15
-- DROP TABLE IF EXISTS t_user;
CREATE TABLE t_user(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	account VARCHAR (50) NOT NULL DEFAULT '' COMMENT '用户名',
	pass_word VARCHAR (50) NOT NULL DEFAULT '' COMMENT '密码',
	real_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT '真实名称',
	email VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'email',
	ip VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'ip',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 't_user';
