CREATE TABLE t_user(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	user_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT '用户名',
	`password` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '密码',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '姓名',
	add_time DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'addTime',
	add_user VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'addUser',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
	update_user VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'updateUser',
	data_status INT (11) NOT NULL DEFAULT -1 COMMENT 'dataStatus',

	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 't_user';
